build.sh ant_sim -graphics opengl
build.sh ant_sim -graphics vulkan
build.sh assets -graphics opengl
build.sh assets -graphics vulkan
build.sh graphics_api -graphics opengl
build.sh graphics_api -graphics vulkan
build.sh multiview -graphics opengl
build.sh multiview -graphics vulkan
build.sh scenes -graphics opengl
build.sh scenes -graphics vulkan
build.sh shadows -graphics opengl
build.sh shadows -graphics vulkan
build.sh tests -graphics opengl
build.sh tests -graphics vulkan
build.sh texture_editing -graphics opengl
build.sh texture_editing -graphics vulkan
build.sh voxels -graphics opengl
build.sh voxels -graphics vulkan